spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/access_governance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    root: INFO
    com.anurag.access: DEBUG

jwt:
  secret: ${JWT_SECRET:VGhpcy1pcy1hLWxvbmctbG9jYWwtand0LXNlY3JldC1rZXktZm9yLWFjY2Vzcy1nb3Zlcm5hbmNl}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}